FROM tensorflow/tensorflow:latest-gpu

RUN apt-get -y update

WORKDIR /app

COPY src /app

RUN pip install jupyterlab

RUN pip install -r requirements.txt

ENTRYPOINT [ "jupyter", "lab", "--allow-root", "--ip=0.0.0.0", "--no-browser"]
